import cs.pcs.taskboards.actions.objects
import cs.pcs.taskboards.issues.objects
import cs.pcs.taskboards.tasks.objects
import cs.pcs.taskboards.actions.display_attributes
import cs.pcs.taskboards.issues.display_attributes
import cs.pcs.taskboards.tasks.display_attributes
import cs.pcs.taskboards.groups
import cs.pcs.taskboards.issues.groups
import cs.pcs.taskboards.tasks.groups
import cs.pcs.taskboards.actions.groups
import cs.pcs.taskboards.interval_board.register
import cs.pcs.taskboards.continuous_board.register
import cs.pcs.taskboards.team_board.register
import cs.pcs.taskboards.team_interval_board.register
import cs.pcs.taskboards.personal_board.register
import cs.pcs.taskboards.sprint_board.register
