#!/usr/bin/env python
# -*- python -*- coding: iso-8859-1 -*-
# $Id$
#
# Copyright (C) 1990 - 2008 CONTACT Software GmbH
# All rights reserved.
# http://www.contact.de/
#
# File:     wsversion.py
# Author:   hth
# Creation: 26.08.08
# Purpose:  workspace manager version and service level

"""
Module wsversion.py

This is the documentation for the wsversion.py module.
"""

__docformat__ = "restructuredtext en"

WS_VERSION = "3.10"

WS_SERVICE_LEVEL = 42


def getVersionTuple(version):
    return tuple([int(charSeq) for charSeq in version.split(".")])


try:
    from svnrevision import REVISION
    # snvrevision.py is generated by buildwsm.bat
    WS_SVN_REVISION = REVISION.replace("\n", "").replace("\r", "")
except ImportError:
    WS_SVN_REVISION = "<unknown>"
