import cs.actions.tasks_plugin
import cs.actions.taskboards.sprint_board.register
import cs.actions.taskboards.team_board.register
import cs.actions.taskboards.personal_board.register
import cs.actions.taskboards.interval_board.register
import cs.actions.taskboards.details
import cs.actions.taskboards.groups
import cs.actions.web
