# !/usr/bin/env powerscript
# -*- python -*- coding: utf-8 -*-
#
# Copyright (C) 1990 - 2020 CONTACT Software GmbH
# All rights reserved.
# http://www.contact.de/

import logging

from cdb import util, sqlapi
from cdb.util import DBInserter
from cs.materials import MaterialStates

LOG = logging.getLogger(__name__)


class MigrateMaterialCatalog(object):

    @staticmethod
    def migrateCatalog():
        """Migrates data from the old material catalog (table werkstoffe) to the new csmat_materials class.
        The values for the new attributes are set according to the following mapping:

            cdb_object_id: automatically generated by platform
            material_id: automatically generated by number generator
            material_index: ""
            cdb_objektart: "csmat_material_std"
            cad_relevant: 0
            short_name: stoff_nr from old material catalog
            name (multi lang): name (multi lang) from old material catalog
            status: 200 if obsolete_flag from old material catalog is 0, 180 otherwise
            cdb_status_txt: 'Released' if obsolete_flag from old material catalog is 0, 'Obsolete' otherwise
            cdb_cdate: NULL
            cdb_mdate: NULL
            cdb_cpersno: NULL
            cdb_mpersno: NULL
        """

        LOG.info("Migrating material catalog to cs.materials ...")
        stmt = """SELECT * FROM werkstoffe"""
        for record in sqlapi.RecordSet2(sql=stmt):

            # DBInserter automatically takes care of cdb_object_id generation and adding it to cdb_objects
            ins = DBInserter("csmat_material")
            new_material_id = "M{:06d}".format(util.nextval("MATERIAL_ID_SEQ"))
            ins.add("material_id", new_material_id)
            ins.add("material_index", '')
            ins.add("cdb_objektart", 'csmat_material_std')
            ins.add("cad_relevant", 0)
            ins.add("short_name", record.stoff_nr)
            ins.add("name_de", record.stoff_d)
            ins.add("name_en", record.stoff_eng)
            ins.add("name_fr", record.stoff_fra)
            ins.add("name_cs", record.stoff_cs)
            ins.add("name_es", record.stoff_es)
            ins.add("name_it", record.stoff_it)
            ins.add("name_ja", record.stoff_ja)
            ins.add("name_ko", record.stoff_ko)
            ins.add("name_pl", record.stoff_pl)
            ins.add("name_pt", record.stoff_pt)
            ins.add("name_tr", record.stoff_tr)
            ins.add("name_zh", record.stoff_zh)
            ins.add("status", MaterialStates.RELEASED if record.obsolete == 0 else MaterialStates.OBSOLETE)
            ins.add("cdb_status_txt", 'Released' if record.obsolete == 0 else 'Obsolete')
            ins.insert()

    @staticmethod
    def updateParts():
        """Updates the teile_stamm table so that parts refer to the new material records."""

        sqlapi.SQL("""UPDATE teile_stamm
                      SET material_object_id=(SELECT cdb_object_id
                                              FROM csmat_material
                                              WHERE short_name=werkstoff_nr)
                      WHERE werkstoff_nr IS NOT NULL AND werkstoff_nr <> ''""")

    @staticmethod
    def updateTitleBlocks():
        """Updates the CAD document title blocks so that they use the new view ce_titleblock_material_v
        to retrieve material specific data for the CAD frames."""

        sqlapi.SQL("""UPDATE rk_values
                      SET relation='ce_titleblock_material_v'
                      WHERE relation IN ('zeichnung_v', 'teile_stamm') AND attribut='werkstoff'""")

    @staticmethod
    def run():
        MigrateMaterialCatalog.migrateCatalog()
        MigrateMaterialCatalog.updateParts()
        MigrateMaterialCatalog.updateTitleBlocks()


if __name__ == "__main__":
    MigrateMaterialCatalog.run()
