from cdb.platform import gui
from cs.platform.web.uisupport import get_ui_link

from cs.vp.bomcreator import GeneratedBOM
from cs.vp.bomcreator.bom import BOMEntry
from cs.vp.bomcreator.web.rest.bomtreemodel import bom_to_tree_row


class BOMModel(object):
    """
    Returns a single BOM (as displayed on the right side of the preview),
    by reading it from the temporary JSON file that is generated by BOMTreeModel.
    """
    def __init__(self, instance_id):
        """
        :param instance_id: temporary UUID of the requested BOM (as returned by BOMTreeModel)
        """
        self.instance_id = instance_id

    def create_result(self, request):
        bom = GeneratedBOM.read_from_disk(self.instance_id)
        columns = self._create_columns(bom)
        rows = self._create_rows(request, bom)
        asm = bom.get_assembly()

        return {"success": True,
                "rows": rows,
                "columns": columns,
                "item_description": asm.GetDescription(),
                "item_icon_link": asm.GetObjectIcon(),
                "item_link": get_ui_link(request, asm),
                "user_hints": bom.user_hints.messages(),
                # we deliver the tree row in case it has changed
                # by the user saving the BOM separately
                "tree_row": bom_to_tree_row(bom)
               }

    def _create_columns(self, bom):
        columns = [{"label": gui.Label.ByKeys("WSM_BOM_status").Text[""],
                    "id": "status",
                    "width": "140px"}]
        factory = bom.get_factory()
        columns_widths = self._calc_column_widths(bom)
        for col_id, header in enumerate(bom.headers):
            width = columns_widths.get(col_id, "40%")
            columns.append({
                "label": header,
                "id": str(col_id),
                "attribute": factory.display_attrs[col_id],
                "editable": factory.is_column_editable(col_id),
                "width": width
            })

        return columns

    def _calc_column_widths(self, bom):
        """
        Distribute the relative width accross the columns
         according to the longest value in every column (incl. headers).
        :param bom: GeneratedBOM
        :return: dict
        """
        max_chars = {}  # by column id
        for col_id, header in enumerate(bom.headers):
            l = len(header)
            max_chars[col_id] = l

        for entry in bom.entries():
            for col_id, (_, val, _old_val) in enumerate(entry.display_row.columns):
                l = len("%s" % val)
                if l > max_chars.get(col_id):
                    max_chars[col_id] = l

        total = float(sum(max_chars.values()))
        relative_widths = {}
        for col_id, max_char in max_chars.items():
            percent = float(max_char) * 100.0 / total
            percent = min(percent, 40.0)  # don't let a single column completely dominate
            relative_widths[col_id] = "{:.0f}%".format(percent)
        return relative_widths

    def _create_rows(self, request, bom):
        rows = []
        for entry_id, entry in enumerate(bom.entries()):
            columns = [entry.status_message]
            columns.extend(v for _expr, v, _old_v in entry.display_row.columns)
            old_columns = [old_v for _expr, _v, old_v in entry.display_row.columns]
            link = None
            try:
                link = get_ui_link(request, entry.item)
            except Exception:  # pylint: disable=W0703
                pass
            row = {"id": str(entry_id),
                   "columns": columns,
                   "old_columns": old_columns,
                   "status": entry.status,
                   "component_link": link,
                   "is_modified": entry.status != BOMEntry.Unchanged
                   }
            rows.append(row)
        return rows
