#!/usr/bin/env powerscript
# -*- mode: python; coding: utf-8 -*-
#
# Copyright (C) 1990 - 2020 CONTACT Software GmbH
# All rights reserved.
# https://www.contact-software.com/

from __future__ import absolute_import

import logging
import traceback

import six
from cdb import CADDOK, i18n
from cdb.platform.gui import Message

# set to True to raise Exceptions server-side instead of serving the client
# user-readable messages (will make unit tests fail!)
DEBUG = False


class ServerResult(object):
    """
    Context manager for less boilerplate when catching server exceptions in a
    client-friendly way.

    CAUTION: ServerResult swallows any Exception raised in its context. It is
    only to be used for client-side error display!

    Usage:

    with ServerResult(error_cls=CreateSharingFailed,
                      default={"sharing": None}) as server:
        server.result["sharing"] = _createSharing(values)

    server.result may now contain an error object:
    {
        "statusText": "Python exception's message",
        "message": "user-readable error message generated by server.error_cls"
    }

    """

    __logerr__ = (
        "Exception in cs.sharing.errors.ServerResult context:" "\n\t{}\n\t{}\n\t{}"
    )

    def __init__(self, error_cls, default=None):
        self.default = default if default else {}
        self.result = {"error": None}
        self.error = False
        self.error_cls = error_cls

    def __enter__(self):
        return self

    def __exit__(self, typ, value, tb):
        result = dict(self.default)
        result.update(self.result)
        self.result = result

        if typ:
            logging.getLogger(__name__).error(
                "%s", self.__logerr__.format(typ, value, traceback.format_tb(tb))
            )
            self.error = True
            self.result.update({"error": dict(self.error_cls(value))})
            return not DEBUG
        return False


def getMessage(message_id):
    message = Message.ByKeys(message_id)

    if not message:
        return None

    result = getattr(message, CADDOK.LANGUAGE, None)
    if result:
        return result

    for fala in i18n.FallbackLanguages():
        result = getattr(
            message, i18n._to_cdb(fala), None  # pylint: disable=protected-access
        )
        if result:
            return result
    return None


class Error(object):
    __message_id__ = None

    def __init__(self, exception):
        self.exception = exception

    def __iter__(self):
        return six.iteritems(
            {
                "message": getMessage(self.__message_id__),
                "statusText": "{}".format(self.exception),
            }
        )


class EmptyRecipientsList(Error):
    __message_id__ = "share_objects.empty_group"


class GetRecipientsFailed(Error):
    __message_id__ = "share_objects.get_recipients_failed"


class CreateSharingFailed(Error):
    __message_id__ = "share_objects.create_sharing_failed"


class GetObjectGroupFailed(Error):
    __message_id__ = "share_objects.get_object_group_failed"


class ResolveGroupFailed(Error):
    __message_id__ = "share_objects.resolve_group_failed"


class GetAttachmentsFailed(Error):
    __message_id__ = "share_objects.get_attachments_failed"


class SaveRecipientsFailed(Error):
    __message_id__ = "share_objects.save_recipients_failed"


class FulltextSearchFailed(Error):
    __message_id__ = "share_objects.fulltext_search_failed"


class DeleteFailed(Error):
    __message_id__ = "share_objects.delete_failed"
