import cs.documents.batchoperations
import cs.documents.effectivities
import cs.documents.web
import cs.documents.web.rest_app
import cs.documents.web.template_create_app
import cs.documents.web.internal_app
import cs.documents.web.dashboard_widget
import cs.documents.docref_resolver_registry
import cs.documents.tasks_plugin
