# -*- mode: python; coding: utf-8 -*-
#
# Copyright (C) 1990 - 2023 CONTACT Software GmbH
# All rights reserved.
# http://www.contact.de/

"""
This module is responsible for generating documentation content to be used by
the documentation portal. The documentation content is taken from *.[f]pickle
files generated by sphinx.

There are two types of content generated:
  1. Documentation html fragments and navigation information inside a sqlite db
  2. Sequential search index of the textual content of the docsets

Each of these content types are generated once for each package.
"""

import json
import logging
import multiprocessing
import os
import shutil
import sys
from datetime import datetime
from urllib.request import pathname2url

import _pickle
import apsw
import whoosh.fields
import whoosh.index
import whoosh.writing
from bs4 import BeautifulSoup
from dateutil.tz import tzlocal
from sphinx.environment.adapters import toctree
from sphinx.util import tags
from whoosh import query

from cs.userassistance import sphinxconf

_logger = logging.getLogger(__name__)

PORTAL_DB_NAME = 'docportal.db'
INDEX_DIR_NAME = '_docindex'
TEASER_PAGE = 'teaser'
MASTER_DOC = 'index'


def main():
    """
    Entry point for running as a script
    """
    params = sys.argv
    if len(params) < 5:
        print('Usage: docindex doc_dir build_dir html,pdf docsetame')
        return 1

    doc_dir = params[1]
    build_dir = params[2]
    builders = params[3].split(',')
    docsetname = params[4]
    return parse_docset(doc_dir, build_dir, builders, docsetname)


def parse_docset(doc_dir, build_dir, builders, docsetname):
    """
    This function builds and updates files for the documentation portal from
    the result of sphinx pickle builder. It will initially create and then
    update the package-wide docportal.db and corresponding docindex folder
    (both usually found in /doc). `docportal.db` contains the content of all
    docsets (excluding binaries like pdf and images), which will be read
    by the docportal to show the documentation for the package. `_docindex`
    contains files required by the search engine of the documentation portal.

    :param doc_dir: Root path of doc portal files
    :param build_dir: Path to the docset containing html and pickle folders
    :param builders: List of the builder formats to determine which formats
           should be offered for download (e.g. pdf)
    :param docsetname: Name of the docset. Used to find the additional
           format binaries.
    """
    portaldb_path = os.path.abspath(os.path.join(doc_dir, PORTAL_DB_NAME))

    portal_db = DocPortalDB(portaldb_path)

    docset = PickleDocset(build_dir, doc_dir)
    docset.scan()
    docset.scan_formats(builders, docsetname)
    docset.write(portal_db.db)


def clean_docsets(doc_dir, exclude=None):
    """
    If parameter `exclude` is provided, then remove all docsets and
    corresponding entries in the search index which are not listed in the
    parameter `exclude`. Otherwise, remove the search index and docportal db
    entirely.

    :param doc_dir: The path to doc directory
    :param exclude: List of docsets to keep (e.g. [`doc/admin/de`])
    """
    portaldb_path = os.path.abspath(os.path.join(doc_dir, PORTAL_DB_NAME))
    if exclude:
        portal_db = DocPortalDB(portaldb_path)
        docsets = portal_db.all_docsets()
        exclude_keys = []
        for ds_handle in exclude:
            keys = ds_handle.split('/', 2)
            # read category of the docset. When the category of a book changes,
            # it will be created anew with a new category relationship.
            # In order to remove the old book with the old category
            # relationship, we have to compare categories as well.
            pickle_path = os.path.join(doc_dir, keys[1], keys[2], 'pickle')
            docset_info = PickleDocset.read_docset_info(pickle_path)
            # In case docset.info could not be found, the docset will be
            # cleared. A valid docset should have a docset.info, otherwise
            # it's category cannot be determined.
            if docset_info:
                cat_title = docset_info.get('category')
                exclude_keys.append((keys[1], keys[2], cat_title))
        docsets_to_delete = (
            ds
            for ds in docsets
            if (ds.relpath, ds.lang, ds.cat_title) not in exclude_keys
        )

        for ds in docsets_to_delete:
            ds.Delete(portal_db.db, clean_categories=True)
            PickleDocset.clear_book_index(doc_dir, ds.name, ds.cat_title, ds.lang)

    else:
        index_path = os.path.abspath(os.path.join(doc_dir, INDEX_DIR_NAME))
        if os.path.exists(index_path):
            shutil.rmtree(index_path)
        if os.path.exists(portaldb_path):
            os.remove(portaldb_path)


class FakeConfig:
    """Fake sphinx config to be used to read the sphinx build environment."""

    def __init__(self, values):
        self.values = values

    def __getattr__(self, name):
        if name not in self.values:
            raise AttributeError(f'No such config value: {name}')
        return self.values[name]

    def __getitem__(self, name):
        return getattr(self, name)

    def __setitem__(self, name, value):
        setattr(self, name, value)

    def __delitem__(self, name):
        delattr(self, name)

    def __contains__(self, name):
        return name in self.values


class FakeBuilder:
    """Fake Builder for generating a toc tree with Sphinx API"""

    def __init__(self):
        self.tags = tags.Tags()

    @staticmethod
    def get_relative_uri(docname, refuri):
        """
        TODO: document me
        :param docname:
        :param refuri:
        :return:
        """
        return refuri


class PickleDocset:
    def __init__(self, docset_path, doc_path):
        self.docset_path = os.path.normpath(docset_path)
        self.pickle_path = os.path.join(self.docset_path, 'pickle')
        self.doc_path = doc_path
        self.src_dir = os.path.join(self.docset_path, 'src')
        self.title = 'No title'
        self.category = 'No category'
        self.name = 'No name'
        self.lang = 'en'
        self.teaser = ''
        self.pages = {}
        self.internal_book = False
        self.extra_formats = {}
        self.relpath = os.path.basename(
            os.path.normpath(os.path.join(docset_path, '..'))
        )
        self.toc = None

    def scan(self):
        self._scan_info()
        self._scan_environment()

    def scan_formats(self, builders, docsetname):
        for b in builders:
            if b not in ['html', 'pickle']:
                self.extra_formats[b] = f'{docsetname}.{b}'

    def _scan_info(self):
        docset_info = self.read_docset_info(self.pickle_path)
        if docset_info:
            self.title = docset_info['title']
            self.category = docset_info['category']
            self.lang = docset_info['language']
            self.name = docset_info['name']
            if self.category == sphinxconf.get_category_name(
                sphinxconf.kDocCategoryInternal, self.lang
            ):
                self.internal_book = True
        else:
            _logger.error('Docset info missing')

    @classmethod
    def read_docset_info(cls, pickle_path):
        info_path = os.path.join(pickle_path, '_static', 'docset.info')
        if os.path.exists(info_path):
            result = {}
            with open(info_path, encoding='utf-8') as fd:
                for line in fd.readlines():
                    key, value = line.split(':', 1)
                    key = str(key.strip().lower())
                    value = str(value.strip())
                    result[key] = value
            return result
        else:
            return None

    def _scan_pages(self, sphinx_env):
        teaser_sources = {}
        left_pages = [MASTER_DOC, TEASER_PAGE]
        visited_pages = []

        # IDEA: Could be sped up a lot with multiprocessing here.
        #       standard imap(), feeding new jobs in as needed.
        while left_pages:
            page_name = left_pages.pop(0)
            visited_pages.append(page_name)
            # read page html/metadata and look for teaser texts
            page_url_name = pathname2url(page_name)
            page_filename = os.path.join(self.pickle_path, page_name + '.fpickle')
            if os.path.exists(page_filename):
                page_data = self._parse_pickle(page_filename, page_url_name)
                # include all references from the page
                left_pages.extend(
                    (
                        ref
                        for ref in page_data['refs']
                        if ref not in visited_pages and ref in sphinx_env.found_docs
                    )
                )
                if page_url_name in [TEASER_PAGE, MASTER_DOC]:
                    teaser_sources[page_url_name] = page_data
                elif page_url_name.endswith('intro'):
                    if 'intro' not in teaser_sources:
                        teaser_sources['intro'] = []
                    teaser_sources['intro'].append((page_url_name, page_data))

                self.pages[page_url_name] = page_data

        if teaser_sources:
            if TEASER_PAGE in teaser_sources:
                self.teaser = self._read_teaser(teaser_sources[TEASER_PAGE], True)
            elif 'intro' in teaser_sources and teaser_sources['intro']:
                found_intro = teaser_sources['intro'][0]
                if len(teaser_sources['intro']) > 1:
                    _logger.warning(
                        '*****************************\n'
                        'Docset contains multiple *intro.rst. '
                        'Using first entry for teaser:'
                    )
                    for base, _ in teaser_sources['intro']:
                        _logger.warning('  %s/%s/%s.rst', self.name, self.lang, base)
                _logger.warning(
                    '*****************************\n'
                    'Deprecation: Using first paragraph from '
                    '%s/%s/%s.rst as teaser text. Please provide a '
                    'teaser.rst file in your book with the teaser '
                    'text instead.\n'
                    '*****************************',
                    self.name,
                    self.lang,
                    found_intro[0],
                )
                self.teaser = self._read_teaser(found_intro[1], True)
            elif MASTER_DOC in teaser_sources:
                self.teaser = self._read_teaser(teaser_sources[MASTER_DOC], True)

    def _scan_environment(self):
        try:
            mts = os.path.getmtime(os.path.join(self.pickle_path, 'last_build'))
            self.mtime = datetime.fromtimestamp(mts, tz=tzlocal()).isoformat()
        except OSError:
            self.mtime = datetime.now(tzlocal()).isoformat()

        env_fn = os.path.join(self.pickle_path, 'environment.pickle')
        if os.path.exists(env_fn):
            with open(env_fn, 'rb') as fd:
                be = _pickle.load(fd)
            self._scan_pages(be)
            for p in be.all_docs:
                pf = pathname2url(os.path.normpath(p))
                timestamp = be.all_docs[p]
                if timestamp and pf in self.pages:
                    self.pages[pf]['mtime'] = datetime.fromtimestamp(
                        timestamp
                    ).isoformat()

            builder = FakeBuilder()
            # noinspection PyTypeChecker
            tt = toctree.TocTree(be).get_toctree_for(
                MASTER_DOC, builder, collapse=False, maxdepth=99, includehidden=False
            )
            self.toc = self._parse_toc(tt)

    @staticmethod
    def _fix_href(href, parent):
        """
         In order to make the links work with the dynamic docportal application,
         the relative link hrefs are changed with this method to be
         relative to the book, rather than the page, as sphinx's html generator
         produces them.
         If the link starts with `../page` it will be changed to `page`.
         If on the other hand, we are on the page `test` and the link starts
         with `./page`, the link href is changed to `test/page`

        :param href: the href of the link or reference
        :param parent: the name of the place, where the link is located.
        :return: adjusted href value
        """
        new_val = href.split('/')
        anchor = ''
        if new_val:
            if new_val[-1].startswith('#'):
                anchor = new_val[-1]
                new_val = new_val[:-1]
            local = not href.lower().startswith('http')
            if new_val and new_val[0] == '.':
                new_val[0] = parent
            elif new_val and new_val[0] == '..':
                new_val = new_val[1:]
            # remove trailing /
            if len(new_val) > 0 and local and not new_val[-1]:
                new_val = new_val[:-1]
        return '/'.join(new_val) + anchor

    def _get_href_from_anchor_tag(self, tag, parent):
        """
         Returns an href of an anchor tag, so that it is relative to the book,
         and not to the page, as the sphinx's html generator produces them.
        :param tag: a beautiful soup anchor tag object
        :param parent: the page name where this anchor tag is located
        :return: the adjusted href value of the anchor tag
        """
        href = tag.get('href', '').split('#')
        if href:
            return self._fix_href(href[0], parent)
        return href

    def _fix_content_link(self, item, attr_name, parent):
        attr_val = item.get(attr_name)
        if attr_val:
            item[attr_name] = self._fix_href(attr_val, parent)

    @staticmethod
    def _fix_search_title(title):
        soup = BeautifulSoup(title, 'lxml')
        return soup.get_text()

    def _process_page_content(self, content, pagename):
        content = content.replace('¶', '')
        soup = BeautifulSoup(content, 'lxml')
        refs = set(
            self._get_href_from_anchor_tag(ref_anchor, pagename)
            for ref_anchor in soup.findAll('a', class_=['internal', 'reference'])
        )
        anchors = soup.find_all('a')
        for anchor in anchors:
            self._fix_content_link(anchor, 'href', pagename)
        images = soup.find_all('img')
        for image in images:
            self._fix_content_link(image, 'src', pagename)
            if image.parent and 'figure' in image.parent.get('class', []):
                if not image.has_attr('class'):
                    image['class'] = []
                image['class'].append('img-responsive')
        for table in soup.find_all('table'):
            table_wrap = soup.new_tag('div', **{'class': 'table-responsive'})
            table.wrap(table_wrap)
            if not table.has_attr('class'):
                table['class'] = []
            table['class'].append('table')
            table['class'].append('table-striped')
            if table.has_attr('border'):
                table['class'].append('table-bordered')
        for bq in soup.find_all('blockquote'):
            bq_wrap = soup.new_tag('div', **{'class': 'table-responsive'})
            bq.wrap(bq_wrap)
        for container in soup.find_all(class_='container'):
            if 'container' in container['class']:
                container['class'].remove('container')
            container['class'].append('rst-container')

        return str(soup), refs

    def _index_page_content(self, pagename):
        page = self.pages.get(pagename)
        body = page.get('body', '')
        if not isinstance(body, str):
            return ''
        body = body.replace('¶', '')
        soup = BeautifulSoup(body, 'lxml')
        h1 = soup.h1
        if h1 and h1.get_text():
            title = h1.get_text()
            if len(title):
                title = title[0].upper() + title[1:]
        else:
            title = self.name

        content = soup.get_text()
        return str(title), str(content)

    def _build_index(self):
        if self.internal_book:
            return
        index = self.get_search_index(self.doc_path)
        self.clear_book_index(self.doc_path, self.name, self.category, self.lang, index)

        procs = max(multiprocessing.cpu_count() - 1, 1)
        # only works with multi segment as woosh is broken otherwise...
        with index.writer(procs=procs, limitmb=512, multisegment=True) as writer:
            book_title = '%s (%s)' % (self.title, self.category)
            book_title = self._fix_search_title(book_title)
            writer.add_document(
                kind='book',
                uri=str(self.name),
                title=str(book_title),
                time=self.mtime,
                body=self._index_page_content(MASTER_DOC)[1],
                name=str(self.name),
                lang=str(self.lang),
                category=self.category,
            )
            for page_name, page in self.pages.items():
                if page_name == TEASER_PAGE:
                    page_title = book_title
                else:
                    page_title = self._fix_search_title(page['title'])
                if page_name in [MASTER_DOC, 'py-modindex', 'search', 'genindex']:
                    # indexed with the book or not for indexing at all
                    continue
                writer.add_document(
                    kind='page',
                    uri=str(page_name),
                    title=str(page_title),
                    time=page['mtime'],
                    body=self._index_page_content(page_name)[1],
                    name=str(page_name),
                    lang=str(self.lang),
                    bookname=str(self.name),
                    category=self.category,
                )
        index.close()

    @classmethod
    def clear_book_index(cls, doc_path, book_name, category_title, lang, index=None):
        """
        Removes all search index entries for a docset/book.

        :param doc_path: Path to doc directory
        :param book_name: Name of a docset
        :param category_title: localized title of the category (from
                               docset.info)
        :param lang: iso code of the language, e.g. 'en'
        :param index: Optional reference to the search index
        """
        if index is None:
            index = cls.get_search_index(doc_path)
        procs = max(multiprocessing.cpu_count() - 1, 1)
        # only works with multi segment as woosh is broken otherwise...
        with index.writer(procs=procs, limitmb=512, multisegment=True) as writer:
            writer.delete_by_query(
                query.Term('kind', 'book')
                & query.Term('name', str(book_name))
                & query.Term('category', str(category_title))
                & query.Term('lang', str(lang))
            )
            writer.delete_by_query(
                query.Term('kind', 'page')
                & query.Term('bookname', str(book_name))
                & query.Term('category', str(category_title))
                & query.Term('lang', str(lang))
            )

    @classmethod
    def get_search_index(cls, doc_path):
        """
        Return a whoosh index object for the package-wide search index found
        in doc_path.

        :param doc_path: Location of parent directory of the search index
                         folder `_docindex`.
        :return: whoosh index object
        """
        index_path = os.path.join(doc_path, INDEX_DIR_NAME)
        if not os.path.exists(index_path):
            os.mkdir(index_path)
        if whoosh.index.exists_in(index_path):
            # open existing search index
            index = whoosh.index.open_dir(index_path)
        else:
            # create new search index
            whoosh_schema = whoosh.fields.Schema(
                kind=whoosh.fields.ID,
                title=whoosh.fields.TEXT(stored=True, field_boost=2.0),
                uri=whoosh.fields.ID(stored=True),
                time=whoosh.fields.STORED,
                body=whoosh.fields.TEXT(stored=True),
                name=whoosh.fields.ID(stored=True),
                lang=whoosh.fields.ID(stored=True),
                bookname=whoosh.fields.ID(stored=True),
                category=whoosh.fields.ID(stored=True),
            )
            index = whoosh.index.create_in(index_path, whoosh_schema)
        return index

    def clear_search_index(self):
        index = self.get_search_index(self.doc_path)
        with index.writer() as writer:
            # write the index from scratch
            writer.mergetype = whoosh.writing.CLEAR

    def _parse_toc(self, dttoc):
        def parse_bullet_list(blist):
            result = []
            toctree_res = []
            for li in blist.children:
                if li.tagname == 'list_item':
                    item = {'children': []}
                    for lii in li.children:
                        if lii.tagname == 'compact_paragraph':
                            parse_paragraph(lii, item)
                        elif toctree_res:
                            item['children'].extend(toctree_res)
                        elif lii.tagname == 'bullet_list':
                            item['children'].extend(parse_bullet_list(lii))
                    result.append(item)

            return result

        def parse_paragraph(p, data):
            if p and p[0].tagname == 'reference':
                ref = p[0]
                refuri = ref['refuri'] or ''
                refuri = refuri.split('#')[0]
                data['anchor'] = (ref['anchorname'] or '').lstrip('#')
                data['uri'] = self._fix_link(refuri)
                data['title'] = ref.astext()

        # check if the doctree is as assumed
        if (
            not dttoc
            or dttoc.tagname != 'compact_paragraph'
            or not dttoc.children
            or dttoc.children[0].tagname != 'bullet_list'
        ):
            return None

        res = dict(
            anchor='',
            uri=MASTER_DOC,
            title=self.pages[MASTER_DOC].get('title', self.title),
        )
        res['children'] = parse_bullet_list(dttoc[0])
        return res if res else None

    @staticmethod
    def _read_teaser(page, as_text=False):
        html = page.get('body')
        if html:
            soup = BeautifulSoup(html, 'lxml')
            ptag = soup.p
            if ptag:
                if as_text:
                    return str(ptag.get_text())
                else:
                    return ''.join(str(t) for t in ptag.children)
        return ''

    @staticmethod
    def _fix_link(link):
        return pathname2url(os.path.normpath(link))

    def _fix_rel_link(self, parent_path, link):
        link = os.path.join(parent_path, link) if link.startswith('.') else link
        return self._fix_link(link)

    def _build_genindex(self, index_data, page_name):
        def link_href(link):
            if len(link) == 2:
                return self._fix_href(link[1], page_name)
            elif len(link) == 3:
                return self._fix_href(link[1] + '#' + link[2], page_name)
            else:
                return ''

        def index_entries(ename, elinks):
            ehtml = '<dt>\n'
            if elinks:
                href = link_href(elinks[0])
                cls = 'main' if elinks[0][0] else ''
                ehtml += f'<a href="{href}" class="{cls}">{ename}</a>\n'
                link_idx = 1
                for link in elinks[1:]:
                    href = link_href(link)
                    cls = 'main' if link[0] else ''
                    ehtml += f'<a href="{href}" class="{cls}">{link_idx}</a>\n' ''
                    link_idx += 1

            else:
                ehtml += f'<span>{ename}</span>\n'
            ehtml += '</dt>\n'
            return ehtml

        html = ''
        for group in index_data:
            html += '<div class="genindex-group">\n'
            html += f'<h2 id="gen-{group[0]}">{group[0]}</h2>\n'
            html += '<div class="genindex-group-entries">\n'
            for entry in group[1]:
                # differs from sphinx versions
                if len(entry[1]) == 2:
                    name, (links, subitems) = entry
                elif len(entry[1]) == 3:
                    name, (links, subitems, _) = entry
                else:
                    _logger.info('genindex format unknown, ignoring entry...')
                    # unknown format, ignore
                    continue
                html += '<div class="genindex-group-entry">\n'
                html += '<dl>\n'
                html += '<dt>\n'
                html += index_entries(name, links)
                html += '</dt>\n'
                if subitems:
                    html += '<dd class="genindex-group-items">\n'
                    for subitem in subitems:
                        html += index_entries(subitem[0], subitem[1])
                    html += '</dd>\n'
                html += '</dl>\n'
                html += '</div>\n'
            html += '</div>\n'
            html += '</div>\n'
        return html

    def _build_modindex(self, index_data, page_name):
        html = ''
        for module in index_data:
            html += '<div class="genindex-module">'
            html += f'<h2 id="gen-{module[0]}">{module[0]}</h2>'
            html += '<div class="genindex-module-entries">'
            for name, group_type, page, anchor, extra, qualifier, description in module[
                1
            ]:
                cls = 'indent' if group_type == 2 else ''
                html += f'<div class="genindex-module-entry {cls}">'
                html += '<div class="title">'
                if page:
                    href = self._fix_href(page + '#' + anchor, page_name)
                    html += f'<a href="{href}">{name}</a>'
                    if extra:
                        html += f'<em>{extra}</em>'
                else:
                    html += f'<span>{name}</span>'
                html += '</div>'
                if qualifier:
                    html += '<div class="addtl">'
                    html += f'<span>{qualifier}</span>'
                    html += f'<em>{description}</em>'
                    html += '</div>'
                html += '</div>'
            html += '</div>'
            html += '</div>'
        return html

    def _parse_pickle(self, path, pname):
        page = {
            'content_type': 0,
            'body': '',
            'title': '',
            'refs': [],
            'next_title': None,
            'next_link': None,
            'prev_title': None,
            'prev_link': None,
            'mtime': 0,
            'meta': {},
        }
        with open(path, 'rb') as pf:
            p = _pickle.load(pf)
            if 'body' in p:
                page['body'], page['refs'] = self._process_page_content(
                    p.get('body'), pname
                )
            elif 'genindexentries' in p:
                page['body'] = self._build_genindex(p.get('genindexentries'), pname)
                page['content_type'] = 1
            elif 'content' in p:
                page['body'] = self._build_modindex(p.get('content'), pname)
                page['content_type'] = 2
            if 'metatags' in p:
                metabody = p.get('metatags')
                soup = BeautifulSoup(metabody, 'lxml')
                for metatag in soup.find_all('meta'):
                    if 'name' in metatag.attrs and 'content' in metatag.attrs:
                        key = metatag['name'].lower()
                        page['meta'][key] = metatag['content']
            if 'title' in p:
                page['title'] = p.get('title')
            if 'next' in p:
                pnext = p.get('next')
                if pnext:
                    page['next_title'] = pnext.get('title')
                    page['next_link'] = self._fix_rel_link(pname, pnext.get('link'))
            if 'prev' in p:
                pprev = p.get('prev')
                if pprev:
                    page['prev_title'] = pprev.get('title')
                    page['prev_link'] = self._fix_rel_link(pname, pprev.get('link'))
        return page

    @staticmethod
    def _category(
        db,
        cursor,
        lang,
        title,
        name=None,
        color=None,
        outline=None,
        icon=None,
        teaser=None,
        order=None,
    ):
        cursor.execute(
            'SELECT id, name, color, outline, icon, teaser, orderval '
            'FROM categories WHERE lang=? AND title=? LIMIT 1;',
            (
                lang,
                title,
            ),
        )
        cat_id = None
        try:
            oldcat = next(cursor)
            cat_id = oldcat['id']
            name = name or oldcat['name']
            color = color or oldcat['color']
            outline = outline or oldcat['outline']
            icon = icon or oldcat['icon']
            teaser = teaser or oldcat['teaser']
            order = order or oldcat['orderval']
        except StopIteration:
            pass
        cursor.execute(
            'INSERT OR REPLACE INTO categories (id, lang, title, name, color,'
            ' outline, icon, teaser, orderval)'
            ' VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)',
            (
                cat_id,
                lang,
                title,
                name,
                color,
                outline,
                icon,
                teaser,
                order,
            ),
        )
        return db.last_insert_rowid()

    def _cur_category(self, db, cursor):
        return self._category(db, cursor, self.lang, self.category)

    def _book(self, db, cursor, cat_id):
        cursor.execute(
            'SELECT id FROM books WHERE category_id=? AND name=? LIMIT 1;',
            (
                cat_id,
                self.name,
            ),
        )
        extra_formats = json.dumps(self.extra_formats)
        try:
            book_result = next(cursor)
        except StopIteration:
            cursor.execute(
                'INSERT INTO books (title, category_id, teaser, name, '
                'relpath, extra_formats) VALUES (?, ?, ?, ?, ?, ?)',
                (
                    self.title,
                    cat_id,
                    self.teaser,
                    self.name,
                    self.relpath,
                    extra_formats,
                ),
            )
            return db.last_insert_rowid()
        else:
            cursor.execute(
                'UPDATE books SET title=?, category_id=?, teaser=?, name=?, '
                'relpath=?, extra_formats=? WHERE id=?;',
                (
                    self.title,
                    cat_id,
                    self.teaser,
                    self.name,
                    self.relpath,
                    extra_formats,
                    book_result['id'],
                ),
            )
            return book_result['id']

    def _write_pages(self, cursor, book_id):
        def bindings():
            for pname, p in self.pages.items():
                yield (
                    pname,
                    p['title'],
                    book_id,
                    p['body'],
                    p['content_type'],
                    p['next_link'],
                    p['next_title'],
                    p['prev_link'],
                    p['prev_title'],
                    p['mtime'],
                )

        try:
            cursor.executemany(
                'INSERT INTO pages (name, title, book_id, body, content_type, '
                'next_link, next_title, prev_link, prev_title, mtime) '
                'VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?);',
                bindings(),
            )
        except Exception as e:
            _logger.error('Failed adding pages %s', e)

    def _navitem(self, db, cursor, item, book_id, parent_id=None):
        if item:
            cursor.execute(
                'INSERT INTO navigation (book_id, uri, anchor, title, '
                'parent_id) VALUES (?, ?, ?, ?, ?)',
                (
                    book_id,
                    item.get('uri'),
                    item.get('anchor'),
                    item.get('title'),
                    parent_id,
                ),
            )
            item_id = db.last_insert_rowid()
            for child in item.get('children', []):
                self._navitem(db, cursor, child, book_id, item_id)

    @staticmethod
    def _localisation(cursor, lang, key, value):
        cursor.execute(
            'INSERT OR REPLACE INTO localisation (lang, key, value)'
            ' VALUES (?, ?, ?)',
            (lang, key, value),
        )

    def write(self, db):
        if self.internal_book:
            return

        # Do the update in a Transaction...
        with db:
            c = db.cursor()
            cat_id = self._cur_category(db, c)
            book_id = self._book(db, c, cat_id)
            c.execute('DELETE FROM pages WHERE book_id = ?', (book_id,))
            self._write_pages(c, book_id)
            c.execute('DELETE FROM navigation WHERE book_id = ?', (book_id,))
            self._navitem(db, c, self.toc, book_id)
            self._build_index()


class DBDocset:
    def __init__(self, title, lang):
        self.title = title
        self.lang = lang
        self.dbid = None
        self.name = None
        self.cat_id = None
        self.cat_title = None
        self.relpath = None

    def Delete(self, db, clean_categories=True):
        # Remove navigation
        db.cursor().execute('DELETE FROM `navigation` WHERE book_id = ?', (self.dbid,))
        # Remove all pages
        db.cursor().execute('DELETE FROM `pages` WHERE book_id = ?', (self.dbid,))

        # Remove the book
        db.cursor().execute('DELETE FROM `books` WHERE id = ?', (self.dbid,))

        # Remove category if empty
        if clean_categories:
            for row in db.cursor().execute(
                'SELECT COUNT(id) AS count FROM `books` '
                'WHERE category_id = ? LIMIT 1;',
                [self.cat_id],
            ):
                if row['count'] == 0:
                    db.cursor().execute(
                        'DELETE FROM `categories` WHERE id = ?;', [self.cat_id]
                    )

        _logger.info(
            'Docset %s (language: %s, category: %s) could not be found, '
            'so it was removed from the database',
            self.title,
            self.lang,
            self.cat_title,
        )


class DocPortalDB:
    def __init__(self, db_path: str):
        self.db = apsw.Connection(db_path)
        self.db.setrowtrace(self._row_factory)
        self.version = self.get_version()
        self.update_schema()

    def all_docsets(self):
        docsets = []
        for row in self.db.cursor().execute(
            'SELECT b.id, b.title, b.name, cat.lang AS lang,'
            ' cat.id AS cat_id, cat.title AS cat_title, relpath,'
            ' extra_formats'
            ' FROM `books` b'
            ' JOIN `categories` AS cat ON b.category_id = cat.id;'
        ):
            ds = DBDocset(row['title'], row['lang'])
            ds.dbid = row['id']
            ds.name = row['name']
            ds.cat_id = row['cat_id']
            ds.cat_title = row['cat_title']
            ds.relpath = row['relpath']
            docsets.append(ds)
        return docsets

    @staticmethod
    def _row_factory(cursor, row):
        columns = (t[0] for t in cursor.getdescription())
        return dict(zip(columns, row))

    def get_version(self):
        c = self.db.cursor()
        c.execute('PRAGMA user_version;')
        try:
            row = next(c)
            return row['user_version'] if 'user_version' in row else 0
        except StopIteration:
            return 0

    def update_schema(self):
        """Create initial schema for docportal db and apply consecutive
        migrations based on the current version of it"""
        if not self.version:
            # initial schema
            c = self.db.cursor()
            c.execute(
                """CREATE TABLE navigation (
                             id integer primary key,
                             book_id integer,
                             uri text,
                             anchor text,
                             title text,
                             parent_id integer,
                             UNIQUE(book_id, uri, parent_id, anchor)
                             ON CONFLICT FAIL
                         );"""
            )
            c.execute(
                """CREATE TABLE categories (
                             id integer primary key,
                             name text,
                             lang text,
                             title text,
                             color text,
                             outline text,
                             icon text,
                             teaser text,
                             orderval integer,
                             UNIQUE(lang, title) ON CONFLICT IGNORE
                         );"""
            )
            c.execute(
                """CREATE TABLE books (
                             id integer primary key,
                             title text,
                             category_id integer,
                             teaser text,
                             name text,
                             relpath text,
                             extra_formats text,
                             UNIQUE(name, category_id) ON CONFLICT IGNORE
                         );"""
            )
            c.execute(
                """CREATE TABLE pages (
                             id integer primary key,
                             name text,
                             title text,
                             book_id integer,
                             body text,
                             content_type integer,
                             next_link text,
                             next_title text,
                             prev_link text,
                             prev_title text,
                             mtime real,
                             UNIQUE (name, book_id) ON CONFLICT REPLACE
                         );"""
            )
            c.execute(
                """CREATE TABLE localisation (
                             id integer primary key,
                             lang text,
                             key text,
                             value text,
                             UNIQUE (lang, key) ON CONFLICT REPLACE
                         );"""
            )
            c.execute('PRAGMA user_version = 1;')


# TODO: Test for html tags stripped from search fields
